### PR TITLE
Feature/test build errors validation

### PR DESCRIPTION
**Pull request by adreyfus**

### CODE REVIEW

**Comment by swederik** [comment]
Hi Aloïs,

I'm sorry but I don't understand this PR. All it does is remove 'let'. What is the reason for that?

**Comment by adreyfus** [comment]
Not for merging. I try to reproduce the behavior denounced in the issue #295 (but the tests do not start, I don't know why).

**Comment by swederik** [comment]
Maybe try cleaning your node modules and doing npm install again? Not sure why they wouldn't run. Is it Windows maybe?

**Comment by adreyfus** [comment]
The problem is not in my computer, but in the github repository.

**Comment by swederik** [comment]
Ah maybe it has something to do with our move from @chafey to @conerstonejs ...

I'll check that. Thanks for the heads up.

**Pull request closed without merging**
