### PR TITLE
Throttle stack scrolls

### PR DESCRIPTION
**Pull request by kofifus**
Using underscore's throttle function, stack scrolls are throttled so that there is no more than one scroll every 50ms. This prevents too many load requests when the user scrolls the stack.

A better solution would be to throttle only when the images are not in the cache but I am not sure how to fit that into the existing framework.

### CODE REVIEW

**Comment by freund17** [comment]
This prevents too many load requests when the user scrolls the stack.

Wouldn't it then make more sense to debounce `loadImage` while the user is scrolling?

**Comment by kofifus** [comment]
Possibly, the best would be to only throttle loading images which are not in the cache I'm not sure how involved that would be ...

But I didn't want to touch loadImage cause I wasn't sure of all the scenarios it may be called ...

**Comment by freund17** [comment]
To find out if a image is in the cache, you just ask the cache:

```js
const cachedImage = cornerstone.imageCache.imageCache['imageId']

if (cachedImage && cachedImage.loaded) {
  // image in cache and fully loaded
  const image = cachedImage.image // access the image
}

if (cachedImage && !cachedImage.loaded) {
  // image currently beeing loaded
}

if (!cachedImage || !cachedImage.loaded) {
  // image not jet loaded
}
```

For the content of `cachedImage` reference:
https://github.com/cornerstonejs/cornerstone/blob/master/src/imageCache.js#L80

The `image`-key gets added a bit later:
https://github.com/cornerstonejs/cornerstone/blob/master/src/imageCache.js#L99

**Comment by dannyrb** [comment]
[Per our recent announcement](https://github.com/cornerstonejs/cornerstoneTools/issues/794) I am going to close this issue. If you feel it would be a good candidate for the latest version of cornerstone-tools, then let's continue to discuss how we might best move forward and add this functionality.

If it is _absolutely critical_ it be added to version 2, we can discuss that as well. Realistically, this will be much more likely to happen if a partner PR is made that targets version 3.

I'm sorry if this inconveniences you. We appreciate the effort you've put in. We realize it can be frustrating to donate work and for it to ultimately not be used. If there's anything we can do to improve in this area, please let us know. We're a small team, open to criticism, and actively trying to improve this process.

**Pull request closed without merging**
