### PR TITLE
Pr/wheelevent prevention

### PR DESCRIPTION
**Pull request by Karl-Heinrich**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
Current behavior is documented in Issue #935

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:
It think we can safely assume that if a user tries to scroll less than one pixel, he is not trying to scroll. The event triggered by the users mouse will emit a vertical scrolling value (deltaY) of either 0 or -0, if he uses his middle mouse button without scrolling. This happens e.g. when pressing down.

However, a few questions remain:
* Where do you document bug fixes?
I've added comments in the code so other developers stumbling upon this will understand what the code does. You might not want to have this commented in the code so if I should remove it, just tell me.
* The test for this is a little bit of a hack - is it ok though?
If the event does not get emitted because we return early, the `assert` part of the test implementation never gets reached and therefore the test will always succeed. If we dont return early, the assert gets reached and it always fails.

### CODE REVIEW

**Comment by JamesAPetts** [comment]
This makes sense and LGTM 👍 .

**Comment by dannyrb** [comment]
> Where do you document bug fixes?

In a perfect world, two places:

- The changelog, updated by using the correct commit syntax
- In a unit test; codifying the fix as a business requirement

The inline comment is fine as well. I'm all for semantic code, where possible, to reduce comments though. Code gets updated, comments don't. For example:

```
  const isMouseWheelEventWithNoScroll = evt.deltaY > -1 && evt.deltaY < 1
  if (isMouseWheelEventThatDoesNotScroll ) {
    return;
  }
```

> The test for this is a little bit of a hack - is it ok though?

I generally prefer that an `expect` validates the behavior, but I'm not sure what the best practice is. If I'd written the test, I probably would have aimed for something like:

```
const cornerstoneMouseWheelEventHandler = jest.fn();

localElement.addEventListener('cornerstonetoolsmousewheel', cornerstoneMouseWheelEventHandler);

// SUT
wheelEventListener.enable(localElement);
localElement.dispatchEvent(middleMouseButtonClickedEvent);

expect(cornerstoneMouseWheelEventHandler.mock.calls.length).toBe(0);
```

Actually, that's still not a unit test, is it? The only thing we _need_ to test here is `wheelEventHandler(evt)`, which you can call directly, and then use a mocked `triggerEvent()` to verify that it was called 0 times.

**Comment by dannyrb** [comment]
@Karl-Heinrich, feel free to make the above changes. As things stand, I'll likely merge this as-is in the next day or two even if you don't. It's a solid improvement! Thanks for taking the time to PR it and add tests ^_^

**Comment by dannyrb** [comment]
@all-contributors please add @Karl-Heinrich for these unit tests and code fixes

**Pull request merged**
