### PR TITLE
fix(src/magnify.js): fix magnify use cornerstone.enable bug whith use…

### PR DESCRIPTION
**Pull request by xingbofeng**
… webgl renderer

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
when use webgl renderer, previous , magnify can render image with wrong wwwc, now is correct.

* **What is the new behavior (if this is a feature change)?**
when use webgl renderer, previous , magnify can render image with wrong wwwc, now is correct.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
NO

* **Other information**:

### CODE REVIEW

**Comment by dannyrb** [comment]
If we can merge and test this change in `vNext` first, I would be happy to merge this backport to v2.

**Comment by xingbofeng** [comment]
hhh, I don't see the v3 branch.@dannyrb

**Comment by dannyrb** [comment]
👋 @xingbofeng 

The `v3` branch is labeled `vNext`. You can find it here: https://github.com/cornerstonejs/cornerstoneTools/tree/vNext

**Comment by xingbofeng** [comment]
@dannyrb ohhh, I create a new [pull request](https://github.com/cornerstonejs/cornerstoneTools/pull/715) branch `vNext`,

**Pull request merged**
