### PR TITLE
feat(imageIdSpecificStateManager): add `set` imageIdToolState function

### PR DESCRIPTION
**Pull request by mix3d**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
A function to replace the tool-specific tool state  in the imageId toolstate global manager.

* **What is the current behavior?** (You can also link to an open issue here)
There is currently no function to consume the same output from `getImageIdToolState()`, (an object like `{'data':[...]}`) which is the state of a specific tool for the given imageId. `addElementToolState()` requires a single item input,
and without a replace function, requires both a `clearImageIdToolState()` step and an iteration over all items to add into the tool's id-specific state, or restoring the ENTIRE imageId tool state manager with data from ALL tools. 

* **What is the new behavior (if this is a feature change)?**
New function on the `globalImageIdToolStateManager` object.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

### CODE REVIEW

**Review by kevinleedrum — APPROVED** [review]
This seems perfectly in line with the existing methods, and I'm sure there are plenty of other teams who could benefit from this.

**Comment by mix3d** [comment]
@dannyrb ?

**Comment by swederik** [comment]
Can we call it `set` instead of replace? Otherwise seems fine to me

**Comment by mix3d** [comment]
@swederik renamed functions. Once the test pass I'll merge it.

**Pull request merged**
