### PR TITLE
Freehand tool bugfix

### PR DESCRIPTION
**Pull request by artemShelest**
Freehand tool has a bug, reproducible from the example page:
1. Draw a closed-loop shape of more than 2 points.
2. Click on the first point of the shape to activate modification mode.
3. Move this point away from its original position.
4. Observe the line still starting from the old position of the point.

### CODE REVIEW

**Comment by swederik** [comment]
Thanks for this!

There is another freehand PR open here, actually: https://github.com/cornerstonejs/cornerstoneTools/pull/344
I'll try to find time to check if that one fixes this issue as well.

**Comment by artemShelest** [comment]
Seems it does not. I can merge after you integrate #344

**Comment by swederik** [comment]
Hi @artemShelest,

@galelis split the commit out and now it's in master. Thanks!

**Comment by dannyrb** [comment]
@swederik, you won't see the changes in the live examples until you publish a new release. We want the examples to reflect the stable/release.

Local dev will show changes if you build and have a dist.

We can talk about a next branch if you'd like that has examples that always reflect unpublished/@next source code?

**Comment by swederik** [comment]
Yeah lets do that, it would be good to at least be able to point to working live examples once fixes are merged.

**Pull request closed without merging**
