### PR TITLE
Chore/add gitbook init

### PR DESCRIPTION
**Pull request by dannyrb**
PR'ing so progress can be watched.

- [x] npm commands to serve / publish docs
- [x] high level readme on how to pull, preview, push docs
- [x] setup custom domain name
- [x] double check github pages and gitbook publishing permissions
- [x] gloss over GitBook settings to make sure we're using everything we care about

This is just to get a _workflow_ in place. Next will likely be a rough overview per project, and a consistent way to add examples/code snippets. Also up for suggestions on which, if any, languages we should support by default.

### CODE REVIEW

**Comment by dannyrb** [comment]
@swederik 

[http://tools.cornerstonejs.org/](http://tools.cornerstonejs.org/) should now be live (if DNS has propagated for you.)

Adding new subdomains for docs associated with other repositories is a two step process:

1. Create a one line CNAME file similar to [this one](https://github.com/cornerstonejs/cornerstoneTools/blob/gh-pages/CNAME) in the `gh-pages` branch of the repo.
2. Add a new CNAME record to the Google Domains DNS record with this pattern:
    - `tools` -- `CNAME` -- `1h` -- `cornerstonejs.github.io.`
    - ^ note the trailing period

The completion of this task creates at least twomore: 

- We should probably create a bare bones "cornerstone.org" repository to use as hosting for our "orgs" website (which can be a basic index to documentation/examples for now).
- SSL would be nice, if only for SEO purposes

It's worth noting that we also have `cornerstonejs.io` should we need it for anything.

**Comment by dannyrb** [comment]
Extra settings, plugins, theme info can be found here:

- https://github.com/GitbookIO/gitbook
- https://toolchain.gitbook.com/
- Examples: https://github.com/GitbookIO/gitbook/blob/master/docs/examples.md

**Comment by dannyrb** [comment]
This is actually pretty cool. I don't think we _need_ docs on how to use/publish our docs. Here is a high level overview, let me know if you want me to squeeze it into the readme, wiki, GitBook, or if it's not worth adding:

*Non-Maintainers:*
- Click "Edit This Page" at the top of the GitBook page you want to edit
- Make edits and preview
- Create pull request

*Maintainers:*
- Run `npm run docs` to preview documentation for your checked out branch
- Run `npm run docs:deploy` to publish your checked out branch's docs
    - Limit to myself and @swederik for now?

**Note:** This may get more complex if we decide to add versions, multiple language support, or documentation for the dev branch (likely overkill for where we're at now)

**Comment by dannyrb** [comment]
@swederik can you take a peak at this and let me know if I can :shipit:?

Not 100% sure we even want to use the GUI provided by GitBook.com (FYI). Merging this should close https://github.com/cornerstonejs/cornerstoneTools/issues/255, and get us on the path to better docs and easier doc contributions.

**Comment by swederik** [comment]
Looks good to me! Merged :-D

**Pull request merged**
