### PR TITLE
Freehand insert and remove

### PR DESCRIPTION
**Pull request by JamesAPetts**
New feature: the ability to add or remove handles after completion:
-- Ctrl + clicking on a line will insert a handle there.
-- Ctrl + clicking on a handle will delete that handle, provided there are more than 3 handles.

Refactoring:
I've done some major refactoring of the tool, as it already significantly more complex than the other region of interest tools.
-- The freehand.js file contains mostly event handling, with the implementation of abstracted functionality found in in utils/freehand/.  I thought a sub-directory is necessary as to not clog up the utils directory, but this could be changed should the team desire.
-- Renamed all instances of "node" to "handle" to stay consistent with the nomenclature across cornerstoneTools.
-- Renamed all instances of "freeHand" to "freehand".

EDIT: Live demo for those interested:
https://deploy-preview-397--cornerstone-tools.netlify.com/examples/freehandroi/

### CODE REVIEW

**Comment by JamesAPetts** [comment]
I'll get on to tackling some of the codeclimate issues now.

**Comment by swederik** [comment]
Looks like there's an import issue. Netlify's deploy preview is failing: 
````
3:15:40 PM: HeadlessChrome 0.0.0 (Linux 0.0.0) ERROR
3:15:40 PM:   {
3:15:40 PM:     "message": "Uncaught Error: Cannot find module \"./freehandIntersect.js\"\nat test/coverage_test.js:22252:179\n\nError: Cannot find module \"./freehandIntersect.js\"\n    at webpackMissingModule (test/coverage_test.js:22252:90)\n    at Object../util/freehand/dropObject.js (test/coverage_test.js:22252:189)\n    at __webpack_require__ (test/coverage_test.js:31:30)\n    at Object../imageTools/freehand.js (test/coverage_test.js:12308:19)\n    at __webpack_require__ (test/coverage_test.js:31:30)\n    at Object../index.js (test/coverage_test.js:16647:17)\n    at __webpack_require__ (test/coverage_test.js:31:30)\n    at Object.../test/coverage_test.js (test/coverage_test.js:11197:14)\n    at __webpack_require__ (test/coverage_test.js:31:30)\n    at ../node_modules/assertion-error/index.js.module.exports (test/coverage_test.js:80:18)",
3:15:40 PM:     "str": "Uncaught Error: Cannot find module \"./freehandIntersect.js\"\nat test/coverage_test.js:22252:179\n\nError: Cannot find module \"./freehandIntersect.js\"\n    at webpackMissingModule (test/coverage_test.js:22252:90)\n    at Object../util/freehand/dropObject.js (test/coverage_test.js:22252:189)\n    at __webpack_require__ (test/coverage_test.js:31:30)\n    at Object../imageTools/freehand.js (test/coverage_test.js:12308:19)\n    at __webpack_require__ (test/coverage_test.js:31:30)\n    at Object../index.js (test/coverage_test.js:16647:17)\n    at __webpack_require__ (test/coverage_test.js:31:30)\n    at Object.../test/coverage_test.js (test/coverage_test.js:11197:14)\n    at __webpack_require__ (test/coverage_test.js:31:30)\n    at ../node_modules/assertion-error/index.js.module.exports (test/coverage_test.js:80:18)"
````

**Comment by JamesAPetts** [comment]
Hmm, this is strange, I've changed the filenames locally but they don't rename on upload. I'll just change the imports for now such that the demo can be displayed at least whilst I try and resolve the issue.

**Comment by JamesAPetts** [comment]
@swederik  It should be ok now.

**Comment by swederik** [comment]
The ctrl + clicking functionality is super cool! Nice work!

**Comment by JamesAPetts** [comment]
Hey @swederik ,

Thanks!

I'm, so close to finishing up the revamped pencil mode, which I feel makes the tool a lot more useable. This branch is safe to merge, however should we hold out a few days and put both features in in one go? I'm happy with either route,

cheers,
JamesAPetts

**Comment by swederik** [comment]
Yeah we can wait

**Comment by JamesAPetts** [comment]
Hey @swederik, just finishing this up, its quite a lot larger so I'll close this and open a new PR.

**Pull request closed without merging**
