### PR TITLE
Add feature of completing freehand during drawing

### PR DESCRIPTION
**Pull request by sisobus**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Trying to implement a function of complete freehand in v3.
I added the public completeDrawing method for the reason of completing handles during drawing.
(e.g. When you need to end the active drawing and complete the polygon if I press enter key.)

And I tested in netlify-example/freehand/index.html

스크린샷 2019-03-20 오후 4 55 00(2)

스크린샷 2019-03-20 오후 4 55 06(2)

* **What is the current behavior?** (You can also link to an open issue here)

There is no completing freehand.

* **What is the new behavior (if this is a feature change)?**

Freehand will be completed if You call completeDrawing method in application-level.

### CODE REVIEW

**Comment by JamesAPetts** [comment]
Hey thanks for this, it's cool and pretty nice to quickly close polygons.

I'm happy to merge this as is, but perhaps it makes sense to just bind this to double click, since its currently unused in the drawing event loop. Seems more natural and intuitive than a key-press. We can do the same thing for touch with double tap also.

What do you think? If you don't have time I can merge this and then I can bind it to double click a bit later.

**Comment by dannyrb** [comment]
@sisobus, can you remove the Yarn lock file?

**Comment by sisobus** [comment]
Hi, It really makes sense. I tested two methods (double click, a key-press) and the method of double click is more comfortable than a key-press. 
So, I did. Thanks!

**Comment by sisobus** [comment]
@dannyrb Of course!

**Comment by JamesAPetts** [comment]
Hey @sisobus , looks awesome, I love it!

**Pull request merged**
