### PR TITLE
Angle and CobbAngle tool: set default 1 for rowPixelSpacing and columnPixelSpacing

### PR DESCRIPTION
**Pull request by aminica**
Only added in the Angle and CobbAngle tool: rowPixelSpacing and columnPixelSpacing default to 1

* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Bug fix

* **What is the current behavior?** (You can also link to an open issue here)
When there are no pixel spacing data of the image, the values of the angle measurements are not able to be calculated, since the getPixelSpacing function returns null for the rowPixelSpacing and columnPixelSpacing values.

* **What is the new behavior (if this is a feature change)?**
Value 1 is used in the angle value calculation if the rowPixelSpacing and/or columnPixelSpacing values are null.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No.

* **Other information**:
Default value 1 is added since in the past every tool had it, but due to some refactoring (in which the getPixelSpacing function was created), this scenario was left out.

### CODE REVIEW

**Comment by dannyrb** [comment]
@JamesAPetts, this doesn't change labeling from `px` to `mm`, but it does assume square pixels. That feels like a safer assumption. Thoughts on merging this?

**Comment by sroopra** [comment]
Any idea when this will be merged? Or is it blocked by the codeclimate issue?

**Comment by aminica** [comment]
So, all checks have now passed. When could we expect the merge?

**Comment by milosdjurdjevic** [comment]
@dannyrb some info on this?

**Comment by aminica** [comment]
@JamesAPetts can we have some update on this?

**Comment by dannyrb** [comment]
Appreciate your patience on this one. I'll merge, but may revert if someone comes forward and forces the non-square pixel argument.

We may eventually want this behavior as an optional flag that can be sit when cornerstone.init() is called.

**Comment by aminica** [comment]
@dannyrb Thank you very much! :)

**Pull request merged**
