### PR TITLE
New Feature: Rotated Elliptical Roi

### PR DESCRIPTION
**Pull request by sisobus**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

feature: New annotation tool similar to elliptical roi

* **What is the current behavior?** (You can also link to an open issue here)

None

* **What is the new behavior (if this is a feature change)?**

rellipticalroi

I implemented a new annotation tool similar to elliptical roi tool.
It contains some functions below.

1. The third handle can move only perpendicular to long axis.
2. A function that check if the point is inside a rotated ellipse
3. It calculates stats of rotated ellipse.
4. Its own svg cursor

You can test in [here](https://examples.sisobus.com/rotated-ellipse)

### CODE REVIEW

**Comment by dannyrb** [comment]
@sisobus, I'm hesitant to add this as a new supported/maintained tool as it's so similar to an existing one. It really feels like an alternative implementation/strategy.

Would you be interested in creating a 3rd party tool repository for this tool, and we can add it to our list of third party tools? If would be interested, please let me know and I can offer assistance.

If you think there is a good reason to replace or modify portions of our similar existing tool, I would also be more than happy to entertain proposals if a good argument is made.

**Comment by sisobus** [comment]
@dannyrb 
Hi, Sorry for late answer. I just read this comment.
I don't know how to create 3rd party library in this project.
But there is a good example (Image Statistics).
So I'd like to try to implement and tell you.

**Comment by dannyrb** [comment]
@sisobus feel free to take a stab! Let me know if you have any questions.
If you end up creating a repository/package, let me know? More than happy to link to it in our docs as another example, and to increase it's exposure ^_^

**Comment by sisobus** [comment]
@dannyrb Hi, 
I implemented this tool in my [repository](https://github.com/sisobus/cornerstoneTools-RotatedEllipticalRoiTool). You can play with this tool in [here](https://examples.sisobus.com/rotated-elliptical-roi/).
Also, I published this package to [npm repository](https://www.npmjs.com/package/cornerstone-tools-rotated-elliptical-roi-tool), You can download via npm or yarn.

I will be very happy if you link to repository. Thanks!

**Comment by dannyrb** [comment]
Awesome work, @sisobus!!! 🎉 
I've updated our readme to include your tool:

https://github.com/cornerstonejs/cornerstoneTools#3rd-party-tool-plugins

If you have any thoughts around how to make tool authoring easier, or how to make your efforts more visible/rewarding, please don't hesitate to reach out!

**Pull request closed without merging**
