### PR TITLE
New feature: Pointer Tool

### PR DESCRIPTION
**Pull request by jlopes90**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)
No

* **What is the new behavior (if this is a feature change)?**
## Pointer Selected (Measurement Active)
selectedMeasurementActive

## Event Pointer (cornerstonetoolspointer)
```
const element = document.querySelector('.cornerstone-element');
const toolType = cornerstoneTools.EVENTS.POINTER;
element.addEventListener(toolType, function (evt) {
  const eventData = evt.detail;
  console.log(eventData);
});
```
#### Console:
eventData

## Try to test (netlify)
```
Array.from(toolButtons).forEach(toolBtn => {
  const toolName = toolBtn.getAttribute('data-tool');
  if (toolName !== 'FreehandRoiSculptor') {
    cornerstoneTools.setToolEnabled(toolName);
  }
});

const pointerTool = cornerstoneTools.PointerTool;
cornerstoneTools.addTool(pointerTool);
cornerstoneTools.setToolActive('Pointer', { mouseButtonMask: 1 });
```

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:
No

### CODE REVIEW

**Comment by jlopes90** [comment]
- [x] Pointer Tool
- [ ] Measurement Selected
- [ ] Test
- [ ] Review

**Comment by dannyrb** [comment]
👋 Hi @jlopes90,
I was able to activate your tool and see it's cursor; however, it did not delete the annotations I clicked. It's also worth noting that we have the `EraserTool` which may have significant overlap with your proposed tool.

**Comment by JamesAPetts** [comment]
@dannyrb  I think the purpose of this PR is not to delete an annotation, but to emit an event about what annotations was clicked on.

Its rather interesting, it feels like there should be one implementation for a "select tool:", with erase, for example, being a strategy.

**Comment by dannyrb** [comment]
While I think this tool would be a nice addition, I don't know how possible it is to accomplish it without changes to core parts of the library. I notice that your tool requires that all other tools be in the `enabled` state. This means that they can't be grabbed/moved using the `pointNearTool` or `pointNearHandle` hooks. Allowing other tools to be `passive` causes the `Pointer Tool`'s "active click" to no longer be sticky.

I would encourage you to bundle this tool into a 3rd party tool, like:

- Image Statistics: [Source](https://github.com/QSolutionsLLC/cornerstone-tool-image-statistics) | [Demo](https://qsolutionsllc.github.io/cornerstone-tool-image-statistics/)
- Rotated Elliptical ROI Tool: [Source](https://github.com/sisobus/cornerstoneTools-RotatedEllipticalRoiTool) | [Demo](https://examples.sisobus.com/rotated-elliptical-roi/)

Or, we can start up a discussion on how we might go about modifying cornerstone-tools to be able to support this kind of functionality in a more useful way.

**Pull request closed without merging**
