### PR TITLE
feat(stackPrefetch.js): Adds events to report stack prefetching progress

### PR DESCRIPTION
**Pull request by mikehazell**
New events `STACK_PREFETCH_IMAGE_DONE` and `STACK_PREFETCH_DONE` are fired when an image is loaded and when the prefetch stack is emptied.

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Feature - fires new events in stackPrefetch.js

* **What is the current behavior?** (You can also link to an open issue here)

No events are fired. The only way to get this information is via polling using setInterval.

* **What is the new behavior (if this is a feature change)?**

When an image is loaded via `stackPrefetch`, `STACK_PREFETCH_IMAGE_DONE` event is fired.
If all images have been loaded `STACK_PREFETCH_DONE` is fired as well.

This enables building a loading progress bar like. See example gif below. The boxes down the right hand side represent each slice in the stack. When a slice is loaded the box opacity changes.

May-02-2019 16-47-53

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No

* **Other information**:

Event data included: 

`STACK_PREFETCH_IMAGE_DONE`

```
element: DOM element - the element on which the event is fired
imageId: String - the id of the loaded image
imageIndex: Int - the position of the loaded image in the stack
stackPrefetch:  prefetch data containing the `indicesToRequest` array
stack: the stack data
```

`STACK_PREFETCH_DONE`

```
element: DOM element - the element on which the event is fired
stackPrefetch:  prefetch data containing the `indicesToRequest` array
stack: the stack data
```

### CODE REVIEW

**Comment by swederik** [comment]
Thanks for the PR!

We have normally been using [`cornerstoneimageloadend`](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/9436d86cb3aa32128e21d9b2f0fb2ad1bdbc5aeb/src/imageLoader/internal/xhrRequest.js#L55) for this. Part of me considers these events unnecessary, but I can understand that this might be easier than monitoring the loading and figuring out which stack has changed.

One minor thing which bothers me is the name STACK_PREFETCH_IMAGE_DONE vs STACK_PREFETCH_DONE. Maybe we could make the first one STACK_PREFETCH_IMAGE_LOADED or something?

**Comment by dannyrb** [comment]
👋 Hi @mikehazell 

This feels like a safe way to expand the API and is worth the expansion for the DX improvement. If you update the naming to match @swederik's suggestions, I'd be happy to merge this PR.

**Comment by mikehazell** [comment]
Hey @dannyrb 👋
Sorry for the slow follow up on this. Have made those changes now.

**Comment by mikehazell** [comment]
Ha, I see you're already on top of this 👍

**Comment by dannyrb** [comment]
Sorry for the delay!
Happy Friday, @mikehazell 🎉

**Pull request merged**
