### PR TITLE
export the base tools for consumption by 3rd parties

### PR DESCRIPTION
**Pull request by mikehazell**
* **Please check if the PR fulfills these requirements**
- [?] The commit message follows our guidelines
- [-] Tests for the changes have been added (for bug fixes / features)
- [-] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

This PR make the BaseTool classes available (or at least more easily accessible) to external libraries.

* **What is the current behavior?** (You can also link to an open issue here)

See issue #878 

* **What is the new behavior (if this is a feature change)?**

Users can now do the following:

```js
import { BaseAnnotationTool } from 'cornerstoneTools';
class MyCustomTool extends BaseAnnotationTool {
   // ...
}
```

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

Nothing breaking. No changes required

### CODE REVIEW

**Comment by dannyrb** [comment]
This might be a "feature" level change. If you run `npm run commit` with staged changes, it should help you craft a commit message that would bump the version level accordingly when we merge this.

**Comment by mikehazell** [comment]
@dannyrb is that something I can do after the fact or should I roll back, re-commit and force push the new commit up?

**Comment by dannyrb** [comment]
@mikehazell: https://help.github.com/en/articles/changing-a-commit-message#amending-older-or-multiple-commit-messages

Or, you can make a small change in the docs/readme and add the message 🤷‍♂️ 
I'm happy if the CI is happy.

**Comment by mikehazell** [comment]
Ha, you read my mind. Or maybe I read yours.

**Comment by dannyrb** [comment]
@mikehazell after some internal discussion, we're leaning toward not merging this and instead focusing on a bit of a doc refresh/revamp. If you'd like to weigh in, if you shoot your email to danny.ri.brown@gmail.com, I can add you to the Cornerstone Maintainer's Slack group.

**Comment by mikehazell** [comment]
Thanks @dannyrb - Email sent.
I think that a docs update is a totally reasonable approach at this point.

**Pull request closed without merging**
