### PR TITLE
fix #1176 Pan and Zoom issue with segmentation on image with non-square pixels

### LINKED ISSUE #1176: Pan and Zoom issue with segmentation on image with non-square pixels
### Prerequisites

* [ ] Which version are you using? (Is it latest?)
yes.
* [ ] Are you reporting to the correct repository?
yes.
* [ ] Did you search existing issues? (Were any related?)
not that I could see.

### Description

The semi-transparent, filled-in sections of a segmentation are not moving consistently with the solid segmentation boundary or the underlying image with non-square pixels.

### Steps to Reproduce the issue

1. When I apply the brush tool using the left mouse button to create a segmentation
2. Then use the middle mouse button to pan or the left mouse button to zoom
3. The semi-transparent pixels in the segmentation do not move consistently with the segmentation boundary or the base image.

**Expected behavior:** The segmentation boundary and semi-transparent infill should undergo the same same translation, providing an accurate view of which pixels have been highlighted.

**Actual behavior:** The boundary maintains it's relative position with the underlying image correctly while the filled in pixels don't maintain there position along the axis with the greater pixel dimension.

### CodeSandbox With Reproduction of Issue:

- https://codesandbox.io/s/segmentation-boundary-and-infill-not-translating-at-the-same-rate-in-images-with-non-square-pixels-obvfp?fontsize=14&hidenavigation=1&theme=dark

### PR DESCRIPTION
**Pull request by MickeyMiao7**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

Bug fix0

* **What is the current behavior?** (You can also link to an open issue here)

#1176

* **What is the new behavior (if this is a feature change)?**

The segmentation boundary and semi-transparent infill undergo the same same translation, providing an accurate view of which pixels have been highlighted.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

no

* **Other information**:

### CODE REVIEW

**Comment by JamesAPetts** [comment]
Hey @MickeyMiao7 , thanks for the PR! This certainly looks like the right thing to do, and we get the same result as before on the square-images in the demo, so that's great.

Have you tried this new version with your non-square pixel examples?

**Comment by MickeyMiao7** [comment]
Hey @JamesAPetts, yes the new version has solved the problem in non-square pixel examples.

I build the `cornerstoneTools.js` locally with the new version and upload it onto codesandfbox, and then import it in the `index.js`. Other codes remain the same as the one in #1176. 

You can see the problem has been solved from the following sandbox link:
 
https://codesandbox.io/s/segmentation-boundary-and-infill-not-translating-at-the-same-rate-in-images-with-non-square-pixels-hcp67?fontsize=14&hidenavigation=1&theme=dark

**Comment by JamesAPetts** [comment]
Thanks for swift reply and the live demo! This looks good to me.

**Comment by JamesAPetts** [comment]
@all-contributors, please add @MickeyMiao7 for this great contribution!

**Comment by dannyrb** [comment]
@all-contributors, please add @MickeyMiao7 for this awesome code

**Comment by JamesAPetts** [comment]
Apparently the bot is not as appreciative as we are haha.

**Pull request merged**
