### PR TITLE
Feature/add a request to the beginning of the stack

### PR DESCRIPTION
**Pull request by adreyfus**
This PR is related to the issue #328.

### CODE REVIEW

**Comment by dannyrb** [comment]
@adreyfus I like this implementation more than the previous one 👍 

Any chance I can get you to add something similar to the following? I'm trying to see if we can try to knock out a simple unit test for each smaller PR that comes through to:

- Get contributors used to writing tests
- Start to slowly increase our test coverage


**Note:** This is just an example, and not tested as working
_/test/requestPool/requestPoolManager_test.js_
```
import { expect } from 'chai';
import requestPoolManager from '../../src/requestPool/requestPoolManager.js';

describe('#requestPoolManager', function () {
  
  beforeEach(() => {
  });

  it('should throw an error when attempting to clear the request stack with an invalid type', function () {
    const nonExistantType = 'NotAnExistingType';
    expect(() => requestPoolManager.clearRequestStack(nonExistantType)).to.throw(new Error('Request type must be one of interaction, thumbnail, or prefetch'));
  });
});
```

**Comment by adreyfus** [comment]
Hi !

I tried your example: test fails with this expectation:

```
#requestPoolManager should throw an error when attempting to clear the request stack with an invalid type FAILED

expected [Function] to throw 'Error: Request type must be one of interaction, thumbnail, or prefetch' but 'Error: Request type must be one of interaction, thumbnail, or prefetch' was thrown
```

In other words, the expected error is thrown but the test fails (I don't understand why).

**Comment by adreyfus** [comment]
To make your example test working, we shall replace 

`expect(() => requestPoolManager.clearRequestStack(nonExistantType)).to.throw(new Error('Request type must be one of interaction, thumbnail, or prefetch'));
`

by

`expect(() => requestPoolManager.clearRequestStack(nonExistantType)).to.throw(Error, 'Request type must be one of interaction, thumbnail, or prefetch');`

**Comment by adreyfus** [comment]
Done :)

**Comment by dannyrb** [comment]
@adreyfus this is good to merge 👍 
@swederik, I've never "Merged" in `cornerstone-core`. I'm going to do so now, but we may need to go over how to automate creating small/new releases coming off merges like this? Similarly, we may want to talk about how best to "batch" releases/features moving forward?

**Comment by dannyrb** [comment]
@adreyfus thanks for all of your hard work. I'm always happy to see a contribution of yours come down the pipe (:

**Pull request merged**
