### PR TITLE
Feature/overlay tool

### PR DESCRIPTION
**Pull request by dannyrb**
## WIP

#780

### CODE REVIEW

**Comment by dannyrb** [comment]
@kofifus, this is a quick port of your `Overlay` PR to version 3's way of creating tools. After https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/239 is merged, we can update this PR with a Test Overlay DICOM and then iterate until we achieve the desired behavior.

**Comment by kofifus** [comment]
great thx

**Comment by kofifus** [comment]
needs a few changes how can I edit this ?

**Comment by dannyrb** [comment]
@kofifus, I've created a `feature/overlay-tool` branch for us to work off of together. When we're happy with the result, we can release to master.

Any merge to this branch update `@cornerstonejs/tools@feature-overlay-tool` on npm:

https://www.npmjs.com/package/@cornerstonejs/tools

This allows us to test and share examples using resources like `codeSandbox`

**Comment by kofifus** [comment]
Thx! can you pls update the codepen to use the cornerstoneWADOImageLoader with (now merged) https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/240

I'll then make overlay.js work again

**Comment by dannyrb** [comment]
@kofifus, this `CodeSandbox` is using the latest `cornerstoneWADOImageLoader` code. I've published the latest code for `cornerstoneWADOImageLoader` under the `@next` tag on `NPM`:

- SandBox: https://codesandbox.io/s/1qj7j8op0l
- Wado Tags: https://www.npmjs.com/package/cornerstone-wado-image-loader

If I'm missing anything, please let me know.

**Comment by kofifus** [comment]
I'm confused ..

here - https://github.com/cornerstonejs/cornerstoneTools/blob/feature/overlay-tool/src/tools/OverlayTool.js#L54

you still use `eventData.image.overlays`

whereas the merged wado version here https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/240/files

does not populate define `image.overlays`

so for the codepen to work it must mean it's not using https://github.com/cornerstonejs/cornerstoneWADOImageLoader/pull/240

**Comment by dannyrb** [comment]
@kofifus, I'll need to double check when I get near a computer, but the WADO code should be latest. If you look at the pen, it's logging the overlay values to the console after grabbing them from the metaDataProvider (not off the image object).

The tool, as is, likely exits early when it sees that eventData.image.overlays is undefined. Maybe one or more lines of text are part of the image's pixeldata?

FWIW, I definitely did not cut a release until after that change was merged. If that isn't the latest published code, then it means I messed up the release (entirely possible - my first time cutting a release for wado)

**Comment by kofifus** [comment]
if the tool exits when starting how come we see the overlay ?

I've committed a new version of the tool to the branch can you please check with that one ?

Thanks!

**Comment by kofifus** [comment]
seems to be some spacing issue, I tried another commit

**Pull request merged**
