### PR TITLE
Freehand Update: drag to edit, passive functionality and bug fix for statistics

### PR DESCRIPTION
**Pull request by JamesAPetts**
New features:
-- Refactored the create functionality into the MOUSE_DOWN_ACTIVATE event, such that the passive functionality could be improved. The tool is now editable whilst the freehand tool is in deactivate mode (i.e. whilst another tool is being used).
-- Editing nodes of the polygon now works based on drag-release rather than click-move-click, as this feels more intuitive.
-- If a drag edit would create a non-simple polygon, the node snaps back to its previous position.

Bug fixes:
-- My statistic features where re-factored by another user when I submitted my last pull request, and a bug was introduced (currently in master branch), whereby statisticsObj.count was global and recalculation due editing the polygon would lead to shrinking erroneous results. This is now fixed.

### CODE REVIEW

**Comment by swederik** [comment]
Live example: https://deploy-preview-392--cornerstone-tools.netlify.com/examples/freehandroi/

**Comment by JamesAPetts** [comment]
Fixed codeclimate Issues.

**Comment by JamesAPetts** [comment]
Fixed a little UI bug where the the ROI wouldn't highlight on mouse over after dragging one time.
All good to go now on my end.

**Comment by JamesAPetts** [comment]
Hey @swederik, I tried tested with the OHIF viewer and all the other tools are unresponsive. This surprised me because /examples/allImageTools/index.html functions correctly.

Have I done something incorrect in the deactivate function? Thanks.

**Comment by JamesAPetts** [comment]
I've found the issue, I was having and it was just how I was including the tool in the viewer, the library is fine as I expected.

Regards,
JamesAPetts

**Comment by swederik** [comment]
Looks great @JamesAPetts!

**Pull request merged**
