### PR TITLE
Feature/scrollToIndex change currentImageIdIndex before calling startLoadingHandler

### PR DESCRIPTION
**Pull request by adreyfus**

### CODE REVIEW

**Comment by dannyrb** [comment]
Is this related to a specific issue in the backlog? Can you provide a real world example of why this change should be merged?

**Comment by adreyfus** [comment]
Hi Danny,

There is no specific issue in the backlog. Should I create one for each new PR ?

The `startLoadingHandler` function permit to display a "Loading" message. 
But if we don't change the currentImageIdIndex before calling it, the frame number will correspond to the previous frame, instead of the currently loading frame.

**Comment by dannyrb** [comment]
It may be a personal preference, but I prefer seeing an issue (or more info in the original PR). A lot of times, an issue gives you room to state:

_For Bugs_

- I expect behavior to be X, but it is Y
- Here is a solution that aligns the behavior with my expectations

_For Features_

- I want to be able to do X, or I want it to be easier to accomplish X, etc.
- Here is how I would approach modifying the code base to make X easier/possible

Both of these routes create a discussion around a change before any code is written. Sometimes there's a better idea for an implementation, or the functionality/behavior is outside the scope of the code base. I guess what I'm getting at is: 

> Discussion is cheap. Writing and revising code is expensive. 

(and nobody likes their PR being rejected). They also provide valuable context that make _reviewing_ an eventual PR easier :P If I have a better understanding of what the PR is trying to accomplish, it's easier for me to provide feedback and merge requests.

**Comment by dannyrb** [comment]
> But if we don't change the currentImageIdIndex before calling it, the frame number will correspond to the previous frame, instead of the currently loading frame.

Does something update the frame number after it has loaded? And does it make more sense for the `currentImageIdIndex` to the be displayed image's index, or the loading image's index?

Does this have any repercussions where we purposefully wait for the previous image to be loaded and displayed before allowing the next image to load/display? (_I may be thinking of a different PR that's floating around_)

**Comment by jdnarvaez** [comment]
I believe you may be thinking of my PR, @dannyrb

**Comment by dannyrb** [comment]
[Per our recent announcement](https://github.com/cornerstonejs/cornerstoneTools/issues/794) I am going to close this issue. If you feel it would be a good candidate for the latest version of cornerstone-tools, then let's continue to discuss how we might best move forward and add this functionality.

If it is _absolutely critical_ it be added to version 2, we can discuss that as well. Realistically, this will be much more likely to happen if a partner PR is made that targets version 3.

I'm sorry if this inconveniences you. We appreciate the effort you've put in. We realize it can be frustrating to donate work and for it to ultimately not be used. If there's anything we can do to improve in this area, please let us know. We're a small team, open to criticism, and actively trying to improve this process.

**Pull request closed without merging**
