### PR TITLE
fix(MagnifyTool.js): too many call _drawZoomedElement leads to memory …

### PR DESCRIPTION
**Pull request by xingbofeng**
…leak because of cornerstone.enable, and fix disable callback of this tool

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

bug fix

* **What is the current behavior?** (You can also link to an open issue here)

1. too many call _drawZoomedElement leads to memory, fix it by add condition.
2. fix disableCallback, because params is element, but not event.

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by xingbofeng** [comment]
and there is a problem that is magnify don't draw any annotation, i think it draw annotations is necessary. if should, i'd like to create the second pull request.

**Comment by dannyrb** [comment]
> and there is a problem that is magnify don't draw any annotation, i think it draw annotations is necessary. if should, i'd like to create the second pull request.

If you're using the `globalToolSyncEnabled` flag, this actually already works. The trick is adding/enabling tools that have annotation data for zoom canvas.

**Comment by dannyrb** [comment]
@xingbofeng, it looks like a `prettier` error is preventing `netlify` and the `build` from completing successfully. If you can resolve, I would be more than happy to merge:

image

**Comment by xingbofeng** [comment]
@dannyrb Thanks, and there is an other problem that my annotation is not added to the magnifyElement,I want to show the annotation, for Example(this is the code I have changed, in my custom cornerstoneTools forked from official):

```javascript
// be called after _drawZoomedElement
_addAllToolsForElement(element) {
    const { tools } = cornerstoneToolsStore.state;
    tools.forEach(tool => {
        if (tool.element !== element) {
            return;
        }
        if (tool instanceof BaseAnnotationTool) {
            this._addNewToolForZoomedElement(tool);
        }
    });
}

_addNewToolForZoomedElement(tool) {
    let { constructor } = tool;
    const { initialConfiguration, name, mode } = tool;
    if (!constructor) {
        const proto = Object.getPrototypeOf(tool);
        constructor = proto.constructor; // eslint-disable-line
    }
    if (!getToolForElement(this.zoomElement, name)) {
        // add the tool to zoomElement
        addToolForElement(this.zoomElement, constructor, initialConfiguration);
        // set the mode
        cornerstoneTools[`setTool${this._upperCaseFirstLetter(mode)}ForElement`](this.zoomElement, name, {});
    }
}

_upperCaseFirstLetter(string) {
    return `${string.charAt(0).toUpperCase()}${string.slice(1)}`;
}
```

If you think it's necessary to add this feature to it, I will change the code, and PR.

**Comment by xingbofeng** [comment]
Oh, thanks, i will try to use `globalToolSyncEnabled ` but not my custom code

**Comment by dannyrb** [comment]
@xingbofeng, here is a quick GIF of a viewer with that flag set:

jOEGyqCqfy

```
cornerstoneTools.init({
  globalToolSyncEnabled: true
})
```

It's a less utilized flag, and it changes the default behavior of `addTool`, `setToolActive` and other methods that apply to all elements. The fact that it does this magic for magnify is entirely by accident.

**Comment by dannyrb** [comment]
@all-contributors, please add @xingbofeng for this bug fix and code

**Comment by xingbofeng** [comment]
Thanks for your help @dannyrb

**Pull request merged**
