### PR TITLE
New Features: hideTextBox, textBoxOnHover and activeColor

### PR DESCRIPTION
**Pull request by jlopes90**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
Feature

* **What is the current behavior?** (You can also link to an open issue here)
No

* **What is the new behavior (if this is a feature change)?**

# hideTextBox and textBoxOnHover

- [x] AngleTool.js
- [x] ArrowAnnotateTool.js
- [x] BidirectionalTool.js
- [x] CircleRoiTool.js
- [x] CobbAngleTool.js
- [x] EllipticalRoiTool.js
- [x] FreehandMouseTool.js
- [x] LengthTool.js
- [x] ProbeTool.js
- [x] RectangleRoiTool.js

How it works?
---------
```
const props = {
     configuration: {
          textBoxOnHover: true,
     }
}
cornerstoneTools.setToolActive('RectangleRoi', props);
```

# color and activeColor

- [x] AngleTool.js
- [x] ArrowAnnotateTool.js
- [x] BidirectionalTool.js
- [x] CircleRoiTool.js
- [x] CobbAngleTool.js
- [x] EllipticalRoiTool.js
- [x] FreehandMouseTool.js
- [x] LengthTool.js
- [x] ProbeTool.js
- [x] RectangleRoiTool.js
- [x] TextMarkerTool.js
- [x] toolColors.js

How it works?
---------
```
var measurement = null;

object.addEventListener('cornerstonetoolsmeasurementadded', function (event) {
     var eventData = event.detail;

     measurement = eventData.measurementData;
});

function setColor(element, measurement, color, setActiveColor = null) {
     // Set Color
     measurement.color = color;

     // Set Active Color
     if (setActiveColor != null) {
          measurement.activeColor = setActiveColor;
     }

     // Cornerstone Update 
     cornerstone.updateImage(element);
}

function setActive(element, measurement, active, setActiveColor = null) {
     // Set Active
     measurement.active = active;

     // Set Active Color
     if (setActiveColor != null) {
          measurement.activeColor = setActiveColor;
     }

     // Cornerstone Update
     cornerstone.updateImage(element);
}
```

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:
No

### CODE REVIEW

**Comment by jlopes90** [comment]
CircleRoiCursor is exactly like ellipticalRoiCursor

**Comment by xingbofeng** [comment]
I have the same question, and i want to set custom textBox, if it can do, it's wonderful

**Comment by dannyrb** [comment]
@jlopes90, thanks for this awesome PR. Sorting through a couple of things over on OHIF, so I'll likely review this early next week.

**Comment by jlopes90** [comment]
TextBox (color, activeColor, hide and hover)
--------
```
textBox: {
     color: undefined,
     activeColor: undefined,
     hide: false,
     hover: false,
}
```

**Comment by dannyrb** [comment]
@jlopes90 is this ready for review?

**Comment by jlopes90** [comment]
> @jlopes90 is this ready for review?

Yes

**Comment by jlopes90** [comment]
I have to change something because I was doing...

```
return cornerstoneTools[toolName].prototype.createNewMeasurement({
	currentPoints: {
		image: true
	}
});
```

I wanted to fetch a class or structure, but it gave error

image

**Comment by jlopes90** [comment]
Do you need this?

```
if (eventData && eventData.currentPoints && eventData.currentPoints.image) {
  logger.error(
	`required eventData not supplied to tool ${
	  this.name
	}'s createNewMeasurement`
  );

  return;
}
```

**Comment by jlopes90** [comment]
@dannyrb, please, re review it. :)

**Comment by jlopes90** [comment]
Update CornerstoneTool 4.0
https://github.com/cornerstonejs/cornerstoneTools/pull/1064

**Pull request closed without merging**
