### PR TITLE
feat: 🎸 Expose isToolActiveForElement

### PR DESCRIPTION
**Pull request by JamesAPetts**
Renamed isToolActive to isToolActiveForElement and expose it as top
level API.

### CODE REVIEW

**Comment by jlopes90** [comment]
What do you think?

```
function isToolModeForElement(element, toolName, mode) {
	const tool = getToolForElement(element, toolName);
	
	return tool.mode === mode;
}
```

**Comment by dannyrb** [comment]
@jlopes90, is this something you think you would use? Are there other convenience methods you feel like we're missing?

**Comment by dannyrb** [comment]
Also, almost always better to discuss in a new issue. It's hard to keep track of topics like this on anything closed/merged.

**Pull request merged**
