### PR TITLE
fix: modifying context of canvas for rendering one tool affects rendering other tools

### LINKED ISSUE #1311: [bug] problems occur when using overlays and annotations at the same time
### Prerequisites

* [x] Which version are you using? (Is it latest?)
* [x] Are you reporting to the correct repository?
* [x] Did you search existing issues? (Were any related?)

### Description
I would like to add an annotation on top of the cornerstone viewport where I loaded the png image using `context.drawImage()`.

However, Zoom or Pan function works normally when annotations are not added, but when annotations are added, the rest of the elements other than annotations do not work normally.

Also, the overlayTool provided by CornerstoneTool has the same problem.

### Steps to Reproduce the issue

1. When scrolling for the first time in CodeSandbox below, Zoom functions normally, such as a dice png image, a white overlay, and a rectangle in the upper left corner.
2. However, Zoom behaves abnormally as soon as you add text annotations by left-clicking the mouse.
3. This is the same with the cornerstoneTool's wwwc, pan, cornerstone rotates, etc.

### CodeSandbox With Reproduction of Issue:

https://codesandbox.io/s/sleepy-paper-uqj4p?fontsize=14&hidenavigation=1&theme=dark

### PR DESCRIPTION
**Pull request by codepage949**
fixes #1311 

* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

fixes bug

* **What is the current behavior?** (You can also link to an open issue here)

before

* **What is the new behavior (if this is a feature change)?**

after

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

no

* **Other information**:

### CODE REVIEW

**Comment by codepage949** [comment]
@dannyrb 

if you checked this pr and had some problem, please let me know what the problem is.

i think this bug is critical so i hope to fix as soon as possible.

**Comment by dannyrb** [comment]
This looks straightforward. Is there a specific tool you're having issues with? Most should be independently using save/restore to prevent this issue.

I can see where this protects from 3rd party tools and any other tools that don't save/restore.

**Comment by codepage949** [comment]
@dannyrb 

below link describes the issue in more detail.

https://github.com/cornerstonejs/cornerstoneTools/issues/1311#issuecomment-697811018

**Pull request merged**
