### PR TITLE
Used getPixelSpacing in FreehandRoiTool

### LINKED ISSUE #1163: Inconsistent area calculation between Freehand and comparable Rectangle ROI
RE: https://github.com/cornerstonejs/cornerstoneTools/pull/1161

Area calculation for Freehand ROI Tool produces different area result than Rectangle ROI Tool despite same point coordinates.

See linked pull request for example and discussion.

CC: @JamesAPetts

### LINKED ISSUE #1224: FreehandRoiTool does not use pixelSpacing from metaData
### Description

Is there a solution to set the pixel spacing for the FreehandRoiTool? I've added a metaDataProvider to cornerstone with `rowPixelSpacing` and `columnPixelSpacing` in it to have measures in `mm` instead of pixels. That worked with the RectangleRoiTool, the AngleTool, and the LengthTool but it didn't work with the FreehandRoiTool that seems to use the properties from the image object.

The tool should use [getPixelSpacing](https://github.com/cornerstonejs/cornerstoneTools/blob/9a71b6281a08c4ac3f6ba463d45dc78a1bf1887d/src/util/getPixelSpacing.js#L3) like the other tools instead of getting the pixel spacing directly from the image. (lines 321, 322, 535 of https://github.com/cornerstonejs/cornerstoneTools/blob/cefbb34e4a651ae49c0b066e36f6ccf0cb6ea89f/src/tools/annotation/FreehandRoiTool.js)

### Steps to Reproduce the issue

1. When I add a metadata provider, the tools should use the provided pixel spacing.

**Expected behavior:** (What you expected to happen)

The measures should be in `mm2` and not in `pixel2`.

**Actual behavior:** (What actually happened)

The measures are in `pixel2`.

### PR DESCRIPTION
**Pull request by sbourouis**
* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)

It fixes #1224 and fixes #1163 

* **What is the current behavior?** (You can also link to an open issue here)

Use the method [getPixelSpacing](https://github.com/cornerstonejs/cornerstoneTools/blob/9a71b6281a08c4ac3f6ba463d45dc78a1bf1887d/src/util/getPixelSpacing.js#L3) like the other tools instead of getting the pixel spacing directly from the image so we can add the pixel spacing to the metaData for non-dicom images.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

No.

### CODE REVIEW

**Comment by sbourouis** [comment]
@JamesAPetts I've updated the tests, please tell me if there's something I have to change.

**Comment by philipp83990** [comment]
hi @sbourouis 
has this been merged already? Doesn't seem to work.

**Comment by sbourouis** [comment]
> hi @sbourouis
> has this been merged already? Doesn't seem to work.

Hi, no, I'm still waiting for code review.

**Comment by swederik** [comment]
Thanks!

One question: why did you remove yourself from the contributors page?

**Comment by sbourouis** [comment]
> Thanks!
> 
> One question: why did you remove yourself from the contributors page?

https://github.com/cornerstonejs/cornerstoneTools/pull/1251#issuecomment-648034180

Hey, I've done it in my last PR following this comment but it seems like the bot didn't add me back to the contributors...

**Pull request merged**
