### PR TITLE
Fix issue 579

### PR DESCRIPTION
**Pull request by daniel2101**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** Bug fix

* **What is the current behavior?** https://github.com/cornerstonejs/cornerstoneTools/issues/579

* **What is the new behavior (if this is a feature change)?** Bug fix, correct rotation
Selección_015
Selección_016

* **Does this PR introduce a breaking change?** No

* **Other information**:

### CODE REVIEW

**Comment by dannyrb** [comment]
Thanks for this! It looks like you have some failing unit tests. If you could resolve them, I would appreciate it.

**Comment by daniel2101** [comment]
Thanks for your comments. I fix unit tests and try again.

**Comment by JamesAPetts** [comment]
Thanks for this @daniel2101 ! Added one commit so this change will cut a new release.

**Comment by dannyrb** [comment]
@all-contributors please add @daniel2101 for this cool code contribution!

**Pull request merged**
