### PR TITLE
feat(LengthTool): Added digits configuration for Length tool

### PR DESCRIPTION
**Pull request by brunoalvesdefaria**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
A new feature which enables the configuration of the amount of digits displayed for the Length tool text box.

* **What is the current behavior?** (You can also link to an open issue here)
The current behavior displays always 2 digits for the Length tool text box.

* **What is the new behavior (if this is a feature change)?**
Now it will be possible to add the `digits` attribute to the Length tool's configuration object in order to change the amount of digits to be displayed by the measurements' text box.

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:
Steps to validade the new behavior:

1. Open the Netlify preview for this PR;
2. Open the browser's developer tools;
3. Change the Length tool configuration from CornerstoneTools' store: `cornerstoneTools.store.state.tools[20].configuration.digits = 1`;
4. Select the length tool and draw length measurements.
5. Note that the amount of digits for the measurements' text boxes have decreased to 1.

### CODE REVIEW

**Comment by sedghi** [comment]
@brunoalvesdefaria Since changes are minor, why not adding them to all annotation tools? Otherwise looks great

**Comment by brunoalvesdefaria** [comment]
> @brunoalvesdefaria Since changes are minor, why not adding them to all annotation tools? Otherwise looks great

Thank you for reviewing it @sedghi!
I didn't include this configuration for BaseAnnotationTool because some of them doesn't display numbers and some display numbers that would not make sense to have decimal digits being displayed.
I think it's better to keep the configuration individual for each tool.

**Comment by mix3d** [comment]
Throwing in my 2 cents: if it's implemented at the base annotation level, each tool can choose what it needs to display and can optionally allow for configuration if it makes sense.

If you only add it to length, then you have to duplicate code when adding it to the circle annotation, for example.

**Comment by brunoalvesdefaria** [comment]
> Throwing in my 2 cents: if it's implemented at the base annotation level, each tool can choose what it needs to display and can optionally allow for configuration if it makes sense.
> 
> If you only add it to length, then you have to duplicate code when adding it to the circle annotation, for example.

I'll summon @swederik to ask his opinion.

We have 3 options:

1. Keep as is (only for Length tool) and replicate the configuration for other tools that might need it.

2. Change the `BaseAnnotationTool` to include digits configuration for all annotation tools (even the ones who doesn't need that, like TextMarkerTool).
If we do that, we would need to append a `constructor` block to the `BaseAnnotationTool` file and include a custom configuration override to add only this `digits` property (might be polluting the file?).

3. Do it at the `BaseTool` level, but it would include digits configuration for all tools (even stack scrolling), which I think it could be confusing. So I think this option is not ideal.

**Comment by swederik** [comment]
I wouldn't do it in BaseAnnotationTool because some tools show more than one value. You might want one level of precision for area and another for mean HU/SUV. I know it's a bit ugly to put it in each tool but it's probably the best option in my opinion.

**Pull request merged**
