### PR TITLE
fix: OverlayTool now considers overlay initial position

### PR DESCRIPTION
**Pull request by fexman**
* **Please check if the PR fulfills these requirements**
- [ ] The commit message follows our guidelines
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ...)
The initial position for DICOM overlays is now considered in OverlayTool.

* **What is the current behavior?** (You can also link to an open issue here)
The origin of DICOM overlays from the overlayPlaneModule was fixed to 0,0.

* **What is the new behavior (if this is a feature change)?**

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)
No

* **Other information**:

### CODE REVIEW

**Comment by dannyrb** [comment]
Thanks for the PR @fexman 
Quick check, do we need to guard against `overlay.x` and `overlay.y` being `NaN`/`undefined`/`null`?

**Comment by fexman** [comment]
Maybe. Should I create another PR and add this?

**Comment by dannyrb** [comment]
Updated here: https://github.com/cornerstonejs/cornerstoneTools/commit/4e430bab6f904c185ca64aeac9b9c06e0a03ec97

**Pull request merged**
