### PR TITLE
Fix the issue which prevents changing bidirectional by handles

### PR DESCRIPTION
**Pull request by evren217**
- Set state.isToolLocked flag to prevent applying the active tool (if another tool is selected) while moving bidirectional handles

### CODE REVIEW

**Comment by dannyrb** [comment]
@galelis, if this has your approval, I'm fine with a merge. I haven't touched the bi-directional tool, so you're the better reviewer here.

@evren217, thanks for using the new `semantic-release` syntax and for this PR! 🚀

**Comment by galelis** [comment]
LGTM! 

@dannyrb why is it merge blocked ? unit tests?

**Comment by dannyrb** [comment]
@galelis, cornerstone-tools has a "team" of users authorized to merge to `master` (as it can automate a new release). Still feeling out the best way to empower users, but also be more deliberate about who can do what.

I've added you to the "Release Publishers" team

**Comment by galelis** [comment]
ooh didn't know about that. 
I was actually asking because of the ci tasks that was failing, thought one of those was blocking the merge.

**Pull request merged**
